### ISSUE TITLE
No LTP_Results for build 16257

### ISSUE THREAD

**Issue by mobluse** [MicrosoftDocs/CommandLine-Docs#124]
It said somewhere that there should be LTP results for all builds of Windows 10, but there is none for the current: Microsoft Windows [Version 10.0.16257.1]. Do you release the tests before or after the release of the OS? I think it would be better if the tests was released before so you could decide if you want to download the new Windows 10 based on the LTP results.

**Comment by sunilmut** [comment]
@mobluse - Thanks for the suggestion. In general, we try to release the LTP results as part of the release notes, but, it does gets missed sometimes. As for [16257](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16257), it does say:

>> LTP Results:
No change since 16251

Additionally, I would not recommend using the LTP results as a measure to determine whether to upgrade or not, because LTP's coverage alone IMO cannot give you that level of confidence. While we try to minimize instability, there will be few things that miss our radar. Alternate options for gaining stability would be to move to the slow ring or move to the stable builds.

**Comment by bitcrazed** [comment]
Thanks for your question @mobluse. Closing for now - feel free to reopen if required.
